FROM python:Latest

#install dependencies

WORKDIR /Badges-Readme

ADD requirements.txt /requirements.txt

RUN pip install -r requirements.txt

#copy code

COPY . /Badges-Readme

CMD ["python", "main.py"]
