FROM python:Latest

#install dependencies

WORKDIR /badges-readme-friendly_rubin

ADD requirements.txt /requirements.txt

RUN pip install -r requirements.txt

#copy code

COPY . .

CMD python /main.py