version: "3.7"
services:
  badge-readme:
    build: .
    container_name: recuring_babbage
    image: docker/dev-environments-default:stable-1
    env_file:
     - .env
    volumes:
      - ./main.py:/main.py
      - ./settings.py:/settings.py
      - ./services:/services
